### ISSUE TITLE
關於讀取 .env 檔的問題

### ISSUE THREAD

**Issue by tsu299** [memochou1993/gpt-ai-assistant#219]
我從.env內去設定以下幾項變數好像沒有被成功讀取到。
```
 APP_INIT_PROMPT: 
 HUMAN_NAME: 
 HUMAN_INIT_PROMPT:
 BOT_NAME: 
 BOT_INIT_PROMPT: 
 BOT_TONE: 
 BOT_DEACTIVATED: 
```
 目前作法是直接將變數寫死在config/index.js內，然後重新build新的image後使用。
